## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [1]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [3]:
m = np.array([1, 2, 3])
n = int (input())
m = np.tile(m, (n,))
m

 6


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [10]:
m = np.arange(20)
m = m[m%2 == 1]
m

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [12]:
m = np.zeros([10, 10])
m[0] = 1
m[9] = 1
m[:, 0] = 1
m[:, 9] = 1
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [13]:
m = np.zeros([8, 8])
m[0::2, 1::2] = 1
m[1::2, 0::2] = 1
m

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [32]:
n = int(input())
def mart (i, j):
    ij = i + j
    return ij
m = np.fromfunction(mart, (n, n), dtype = int)
m

 5


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [43]:
m = np.array([1, 2, 3, 4, 7])
n = np.array([5, 6, 7, 8, 9])
print (np.dot(m, n))
k = np.random.randint(16, size = (5, 4))
j = np.random.randint(16, size = (4, 4))
print (k)
print (j)
print (np.dot(m, k))
print (np.dot(k, j))

133
[[15  7  2 14]
 [ 2  2 13  0]
 [11  3 11  0]
 [15  2  8 15]
 [10  6  0  4]]
[[13  3  2  8]
 [10  7  5 15]
 [10  1  0  4]
 [ 8 10 10 15]]
[182  70  93 102]
[[397 236 205 443]
 [176  33  14  98]
 [283  65  37 177]
 [415 217 190 407]
 [222 112  90 230]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [44]:
cs = np.arange(0, 1.05, 0.05)
s = np.sin(cs)
c = np.cos(cs)
cs = np.hstack((c, s))
cs

array([1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
       0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
       0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
       0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309,
       0.54030231, 0.        , 0.04997917, 0.09983342, 0.14943813,
       0.19866933, 0.24740396, 0.29552021, 0.34289781, 0.38941834,
       0.43496553, 0.47942554, 0.52268723, 0.56464247, 0.60518641,
       0.64421769, 0.68163876, 0.71735609, 0.75128041, 0.78332691,
       0.8134155 , 0.84147098])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [45]:
m = np.random.rand(3,5) * 4 - 1
m

array([[ 1.82674721,  1.2379098 ,  0.36432166,  0.25286005, -0.20733226],
       [ 2.96711285, -0.10214016, -0.34928927,  1.4212747 ,  1.37983667],
       [ 1.78053035,  1.96353512,  1.61528186, -0.8987967 ,  0.45554299]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [61]:
A = np.random.randint(12, size = (4, 3))
print (A)
print ('Сумма по столбцам: ', A.sum(axis = 0))
print ('Сумма по строкам: ', A.sum(axis = 1))
print ('Сумма всех элементов:', A.sum(axis = None))
print ('Среднее значение:', np.average(A))
print ('стандартное отклонение: ', A.std())
print ('дисперсия строк: ', np.var(A, axis = 1))
print ('дисперсия столбцов: ', np.var(A, axis = 0))

[[8 1 4]
 [4 3 6]
 [0 2 8]
 [7 5 0]]
Сумма по столбцам:  [19 11 18]
Сумма по строкам:  [13 13 10 12]
Сумма всех элементов: 48
Среднее значение: 4.0
стандартное отклонение:  2.7688746209726918
дисперсия строк:  [ 8.22222222  1.55555556 11.55555556  8.66666667]
дисперсия столбцов:  [9.6875 2.1875 8.75  ]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [70]:
A = np.random.randint(18, size = (6, 3))
print (A)
m = A.mean(axis = 1)
n = A.std(axis = 1)
print ((A - A.mean(axis = 1).reshape(-1, 1))/A.std(axis = 1).reshape(-1, 1))

[[11 11 10]
 [ 9 16  8]
 [ 9  0 10]
 [ 8  4 10]
 [ 8  6  4]
 [14  1  1]]
[[ 0.70710678  0.70710678 -1.41421356]
 [-0.56195149  1.40487872 -0.84292723]
 [ 0.59299945 -1.4083737   0.81537425]
 [ 0.26726124 -1.33630621  1.06904497]
 [ 1.22474487  0.         -1.22474487]
 [ 1.41421356 -0.70710678 -0.70710678]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [81]:
A = np.random.randint(12, size = (2, 6))
A[A[:, 2]. argsort()]

array([[10,  7,  6,  9,  0,  7],
       [ 1, 10, 10,  3,  6,  3]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [84]:
B = np.random.randint(12, size = (4, 3))
C = np.random.randint(12, size = (6, 2))
A = np.random.randint(12, size = (3, 4))
B = np.dot(A.T, A)
print (B)
C = np.dot(A, A.T)
print (C)

[[200 140 100  50]
 [140 117  82  38]
 [100  82  88  60]
 [ 50  38  60  49]]
[[141  46 170]
 [ 46  73  58]
 [170  58 240]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [73]:
np.trace(B)


393

In [74]:
np.trace(C)

393

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [77]:
np.linalg.det(B)

-2.405996194355975e-11

In [78]:
np.linalg.det(C)

87199.99999999988

In [85]:
np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

In [86]:
np.linalg.matrix_rank(A)

3

In [87]:
np.linalg.matrix_rank(B)

3

In [88]:
np.linalg.matrix_rank(C)

3

In [90]:
a, b = np.linalg.eig(B)
a

array([3.85106140e+02, 5.55428916e+01, 1.33509687e+01, 1.79915704e-15])

In [89]:
x, y = np.linalg.eig(C)
x

array([385.10613969,  13.35096871,  55.5428916 ])

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>